// Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026-present Datadog, Inc.

'use strict';
function serverArt(){return `<svg class="server-art" viewBox="0 0 150 120" aria-hidden="true"><ellipse cx="77" cy="103" rx="56" ry="10" fill="#42633b" opacity=".06"/><path class="platform" d="M6 83 L70 48 L144 87 L78 120 Z" fill="#dbe5cf"/><path d="M31 29 L72 6 L118 32 L75 57 Z" fill="#c6d7b1"/><path d="M31 29 L75 57 V99 L31 73 Z" fill="#94ad7d"/><path d="M75 57 L118 32 V75 L75 99 Z" fill="#708d60"/><path d="M40 48 L64 62 V69 L40 55 Z M40 64 L64 78 V85 L40 71 Z" fill="#e3edcf"/><path d="M85 63 L107 51 V58 L85 71 Z M85 78 L107 66 V72 L85 85 Z" fill="#b1c896"/><circle cx="105" cy="44" r="2" fill="#e5efa5"/></svg>`;}
function clientArt(){return `<svg class="source-art" viewBox="0 0 120 90" aria-hidden="true"><path d="M6 58 L54 33 L112 64 L63 89 Z" fill="#dce5d3"/><path d="M24 20 L62 7 L96 27 L58 44 Z" fill="#cdddbd"/><path d="M24 20 L58 40 V67 L24 47 Z" fill="#91aa7d"/><path d="M58 40 L96 21 V49 L58 67 Z" fill="#718f62"/><path d="M31 29 L50 40 V51 L31 40 Z" fill="var(--client)"/><circle cx="82" cy="43" r="2" fill="#e8f2d6"/></svg>`;}
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#7f9d61','#b7865a','#79a4a7','#aa84aa','#bf927b','#738fbd','#aaa055','#849585'],color=id=>colors[id%8];
const num=(v,d=0)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const time=ms=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${(ms/1000%60).toFixed(1).padStart(4,'0')}`;
const ys=[95,265,435,625],sourceY=(i,n)=>n===1?340:105+i*505/(n-1),phases={ready:'#7f9d61',unavailable:'#b56f57',checking:'#c3a14b',rebuilding:'#b28b50',empty:'#aab49e'};
let state=null,busy=false,polling=false,connected=false,revision=0,selected={kind:'replica',id:0},controlsKey='',mapKey='',decisionKey='',seenMotion=0,particles=[],lastFrame=0,lastProgress=0,controlsDirty=false,controlsConfig='';
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scripts={sandbox:'Inject faults directly on the map. The policy sees health observations only.',single_crash:'A crashes at 10s; it restarts at 65s. Watch replacement and readiness checks.',rebuild_pressure:'A crashes at 10s. Traffic and request cost surge at 16s, recover at 50s. A restarts at 65s.',second_failure:'A crashes at 10s, then B at 18s. A restarts at 65s and B at 80s.'};
function showError(s){$('error').textContent=s||'';$('error').hidden=!s;}
function nodeLabel(n){return n.phase==='ready'?(n.serving?'Serving':'Ready · excluded'):n.phase==='empty'?'Spare slot':n.phase[0].toUpperCase()+n.phase.slice(1);}
function render(){
 $('connection').textContent=connected?'● Engine connected':'Engine disconnected';
 $('connection').dataset.connected=String(connected);
if(!state)return;
 renderForecast(state.forecast, "Recovery pressure", state.policy, busy || !connected);
 const ended=state.at_ms>=state.horizon_ms;
 $('evidence-source').hidden=state.evidence_source!=='datadog';$('evidence-source').textContent=`Jev evidence: Datadog · Run: ${state.simulation_run||'—'} · Live charts below show simulation state`;
 $('clock').textContent=time(state.at_ms);if($('duration'))$('duration').textContent=`/ ${String(Math.floor(state.horizon_ms/60000)).padStart(2,'0')}:00`;$('run-status').textContent=ended?'COMPLETE':state.paused?'PAUSED':'RUNNING';$('play').textContent=state.paused?(state.at_ms?'▶ Resume traffic':'▶ Start traffic'):'Ⅱ Pause traffic';
 ['play','step'].forEach(id=>$(id).disabled=busy||!connected||ended);$('reset').disabled=busy||!connected;$('step').disabled ||= state.evidence_source==='datadog';
 $('policy').value=state.policy;$('policy').disabled=busy||!connected||state.evidence_source==='datadog';$('policy').querySelector('[value=jev]').disabled=!state.available;
 $('run-scenario').disabled=busy||!connected||state.scenario==='sandbox';$('scenario').value=state.scenario;$('scenario').disabled=busy||!connected;$('scenario-description').textContent=scripts[state.scenario];$('bandwidth').value=String(state.bandwidth_limit);$('bandwidth').disabled=busy||!connected;
 document.querySelectorAll('[data-speed]').forEach(b=>{b.setAttribute('aria-pressed',+b.dataset.speed===state.speed);b.disabled=busy||!connected||(state.evidence_source==='datadog'&&+b.dataset.speed!==1);});
 $('status').textContent=state.paused&&state.pending?'Paused · pending judgment applies on resume':state.status;if(state.evidence_source==='datadog')$('status').textContent+=' · '+state.telemetry_status;$('calls').textContent=state.policy==='jev'?`${state.calls} evaluations`:'Fixed thresholds · no inference';
 const t=state.totals,e=state.evidence,c=state.cost,partial=c.missing_usage_calls+c.unpriced_calls;
 $('success').textContent=t.essential_arrivals?num(100*t.essential_succeeded/t.essential_arrivals,1)+'%':'—';$('success').title=`${t.essential_succeeded} succeeded / ${t.essential_arrivals} offered; in-flight requests are included in offered`;
 $('latency').textContent=e.long_window.p95_ms?num(e.long_window.p95_ms)+'ms':'—';$('ready').textContent=state.replicas.filter(n=>n.phase==='ready').length+' / 3';$('rejected').textContent=num(t.rejected);
 const r=state.recovery;$('recovery-time').textContent=r?.finished_at?num((r.finished_at-r.started_at)/1000,1)+'s':r?num((state.at_ms-r.started_at)/1000,1)+'s':'—';
 $('cost').textContent=c.priced_calls===0&&partial?'—':`$${num(c.estimated_usd,6)}${partial?'*':''}`;$('cost-details').textContent=`${c.calls} calls · ${num(c.input_tokens)} input tokens · ${c.priced_calls} priced responses · ${c.missing_usage_calls} calls without usage · ${c.unpriced_calls} unknown model prices. ${partial?'The estimate is partial.':''}`;
 $('intervention').hidden=!state.intervention;$('client-count').textContent=`${state.clients.length} / 8`;$('add-client').disabled=busy||!connected||state.clients.length>=8;
 renderMap();renderControls();renderDetail();renderRecovery();renderDecisions();renderTrend();
 $('totals').textContent=`${num(t.succeeded)} succeeded · ${num(t.failed)} failed · ${num(t.retries)} retries`;
}
function renderMap(){const ids=state.clients.map(c=>c.id).join(',');
 if(ids!==mapKey){mapKey=ids;$('map-clients').innerHTML=state.clients.map((c,i)=>`<button class="map-source" data-client="${c.id}" style="left:14%;top:${sourceY(i,state.clients.length)/7.2}%;--client:${color(c.id)}" aria-label="Configure Client ${c.id+1}">${clientArt()}<strong>Client ${c.id+1}</strong><span class="source-rate"></span></button>`).join('');
 $('map-replicas').innerHTML=state.replicas.map((n,i)=>`<button class="map-node" data-replica="${i}" style="left:76%;top:${ys[i]/7.2}%" aria-label="Inspect Replica ${String.fromCharCode(65+i)}"><span class="load-pile"></span>${serverArt()}<span class="fault-tag" hidden></span><strong>${esc(n.name)}</strong><span class="replica-state"><i></i><span></span></span><span class="mini-resource"><span>LOAD</span><i><b></b></i><small></small></span><span class="replica-note"></span></button>`).join('');
 }
 $('topology').classList.toggle('many-clients',state.clients.length>5);
 const paths=[...state.clients.map((c,i)=>({d:`M140 ${sourceY(i,state.clients.length)} C245 ${sourceY(i,state.clients.length)} 290 340 430 340`,active:true})),...state.replicas.map((n,i)=>({d:`M430 340 C560 340 590 ${ys[i]} 760 ${ys[i]}`,active:n.serving,broken:n.faults.client_partition||n.faults.crashed}))];
 $('flow-paths').innerHTML=paths.map(p=>`<g opacity="${p.active?1:.25}"><path d="${p.d}" class="track-shadow"/><path d="${p.d}" class="track"/><path d="${p.d}" class="track-center ${p.broken?'blocked-track':''}"/></g>`).join('');
 state.clients.forEach(c=>{const b=document.querySelector(`#map-clients [data-client="${c.id}"]`);b.querySelector('.source-rate').textContent=c.config.enabled&&c.config.rate?`${num(c.config.rate,1)} req/s · ${c.config.cost_ms}ms`:'Paused';b.classList.toggle('source-paused',!c.config.enabled||!c.config.rate);b.setAttribute('aria-pressed',selected.kind==='client'&&selected.id===c.id);});
 state.replicas.forEach((n,i)=>{const b=document.querySelector(`#map-replicas [data-replica="${i}"]`),jobs=state.requests.filter(r=>r.node===i),obs=state.evidence.replicas[i];b.dataset.phase=n.phase;b.style.setProperty('--phase',phases[n.phase]);b.setAttribute('aria-pressed',selected.kind==='replica'&&selected.id===i);b.querySelector('.replica-state span').textContent=nodeLabel(n);b.querySelector('.mini-resource b').style.width=jobs.length/32*100+'%';b.querySelector('.mini-resource small').textContent=jobs.length+'/32';b.querySelector('.load-pile').innerHTML=jobs.slice(0,20).map(r=>`<i style="background:${color(r.client)}"></i>`).join('');
 const f=n.faults,tags=[f.crashed?'CRASHED':null,f.client_partition?'READ LINK CUT':null,f.transfer_partition?'TRANSFER CUT':null,f.slowdown>1?num(f.slowdown)+'× SLOW':null,f.error_rate>0?num(f.error_rate*100)+'% ERRORS':null,f.stale?'STALE':null].filter(Boolean);b.querySelector('.fault-tag').hidden=!tags.length;b.querySelector('.fault-tag').textContent=tags[0]||'';b.querySelector('.fault-tag').title=tags.join(' · ');
 const latest=state.decisions.find(x=>x.status==='applied'&&(x.action?.replica===i||x.action?.target===i));b.querySelector('.replica-note').textContent=latest&&state.at_ms-latest.at_ms<6000?latest.label:obs.queue_depth?`${obs.queue_depth} waiting`:n.phase==='empty'?'Available for a replacement':'';
 });
 $('serving-mode').textContent=state.essential_only?'Essential reads only':'Normal service';$('retry-mode').textContent=state.retries_enabled?'Retries ≤ 1 · 10% budget':'Retries off';$('judge-status').textContent=state.pending?(state.paused?'Judgment pending':'Jev evaluating…'):state.policy==='jev'?'Jev + Reflex':'Fixed + Reflex';$('judge-status').classList.toggle('pending',state.pending);
 const r=state.recovery;$('transfer-path').innerHTML=r&&['rebuilding','verifying'].includes(r.phase)?`<path d="M800 ${ys[r.source]-10} C950 ${ys[r.source]-10} 950 ${ys[r.target]-10} 800 ${ys[r.target]-10}" class="transfer-line"/><text x="947" y="${(ys[r.source]+ys[r.target])/2}" fill="#9c7745" style="font-size:var(--dd-text-xs)" text-anchor="end">${num(r.progress_mb)}% · ${num(r.rate)} MB/s</text>`:'';
}
function renderControls(force=false){if(selected.kind==='client'&&!state.clients.some(c=>c.id===selected.id))selected={kind:'client',id:state.clients[0].id};const key=selected.kind+selected.id+':'+state.clients.map(c=>c.id).join(',');const config=JSON.stringify(selected.kind==='replica'?state.replicas[selected.id].faults:state.clients.find(c=>c.id===selected.id).config);if(!force&&key===controlsKey&&(controlsDirty||config===controlsConfig))return;controlsKey=key;controlsConfig=config;controlsDirty=false;
 $('inspector-picker').innerHTML=state.replicas.map(n=>`<button data-replica="${n.id}" aria-label="Select Replica ${String.fromCharCode(65+n.id)}" aria-pressed="${selected.kind==='replica'&&selected.id===n.id}">${String.fromCharCode(65+n.id)}</button>`).join('')+state.clients.map(c=>`<button data-client="${c.id}" aria-label="Select Client ${c.id+1}" aria-pressed="${selected.kind==='client'&&selected.id===c.id}">C${c.id+1}</button>`).join('');
 if(selected.kind==='replica'){const n=state.replicas[selected.id],f=n.faults;$('inspector-title').textContent=n.name;$('inspector-help').textContent='Inject faults on this replica. Changes apply immediately to the simulated world.';$('controls').innerHTML=`<form id="fault-form">${[['crashed','Crash replica'],['client_partition','Isolate read traffic'],['transfer_partition','Isolate recovery transfers'],['stale','Make snapshot stale']].map(([k,label])=>`<label class="fault-switch">${label}<input type="checkbox" role="switch" name="${k}" aria-label="${label}" ${f[k]?'checked':''}></label>`).join('')}<div class="control-grid"><label>Slowdown ×<input aria-label="Replica slowdown" name="slowdown" type="number" min="1" max="10" step="0.5" value="${f.slowdown}" required></label><label>Error rate %<input aria-label="Replica error rate" name="error_rate" type="number" min="0" max="100" value="${f.error_rate*100}" required></label></div><div class="form-actions"><button class="primary" type="submit">Apply faults</button><button type="button" id="heal">Clear faults</button></div></form>`;
 }else{const c=state.clients.find(c=>c.id===selected.id),f=c.config;$('inspector-title').textContent=`Client ${c.id+1}`;$('inspector-help').textContent='Set this source’s traffic and request cost. Changes affect future arrivals.';$('controls').innerHTML=`<form id="client-form"><label class="fault-switch">Send traffic<input type="checkbox" role="switch" name="enabled" aria-label="Enable client traffic" ${f.enabled?'checked':''}></label><div class="control-grid"><label>Requests / sec<input name="rate" aria-label="Client requests per second" type="number" min="0" max="40" step="0.5" value="${f.rate}" required></label><label>Work / read (ms)<input name="cost_ms" aria-label="Client request cost" type="number" min="50" max="1000" step="50" value="${f.cost_ms}" required></label><label>Essential %<input name="essential_pct" aria-label="Client essential percent" type="number" min="0" max="100" value="${f.essential_pct}" required></label></div><div class="form-actions"><button class="primary" type="submit">Apply client</button><button type="button" id="remove-client" ${state.clients.length===1?'disabled':''}>Remove client</button></div></form>`;}
}
function renderDetail(){if(selected.kind==='replica'){const n=state.evidence.replicas[selected.id];$('live-detail').innerHTML=`Observed: ${esc(n.phase)} · snapshot v${n.snapshot_version}<br>${n.in_flight} in flight · ${n.queue_depth} queued<br>Heartbeat ${num(n.heartbeat_age_ms/1000,1)}s ago<br>${n.responses_5s?num(n.success_rate_5s*100)+'% successful · last 5s':'No responses in last 5s'}`;}else{$('live-detail').textContent='Four concurrent reads per replica; requests above that wait. Arrivals are processed on 50 ms ticks while preserving the configured average rate.';}}
function renderRecovery(){const r=state.recovery;$('operation-title').textContent=r?`${String.fromCharCode(65+r.source)} → ${String.fromCharCode(65+r.target)} · ${r.phase}`:'No rebuild in progress';$('operation-progress').style.width=(r?.progress_mb||0)+'%';$('operation-detail').textContent=r?(r.reason||`${num(r.progress_mb,1)} / 100 MB transferred. ${r.phase==='verifying'?'Verifying the snapshot before marking the target ready.':r.phase==='completed'?'Snapshot verified. The replica can now be added to serving.':'A transfer reduces read capacity at both endpoints.'}`):'The policy can rebuild a replacement after redundancy falls below three.';$('operation-stats').innerHTML=r?`<span>${num(r.rate)} MB/s allocated</span><span>${num(Math.min(.7,r.rate/16*.7)*100)}% endpoint capacity during transfer</span>`:'';}
function renderDecisions(){const latest=state.decisions[0];$('decision-title').textContent=latest?.label||'Waiting for evidence';$('decision-detail').textContent=latest?`${time(latest.at_ms)} · ${latest.status} · ${latest.reason}`:'Start traffic, then inject a failure.';$('inspect-latest').hidden=!latest;const key=state.decisions.map(d=>d.id).join(',');if(key===decisionKey)return;decisionKey=key;$('decisions').innerHTML=state.decisions.map(d=>`<tr><td>${time(d.at_ms)}</td><td>${esc(d.label)}</td><td class="${['rejected','evaluation_error'].includes(d.status)?'error':''}">${esc(d.status)}</td><td>${d.result?.confidence!=null?num(d.result.confidence*100,1)+'%':'—'}</td><td><button data-decision="${d.id}" aria-label="Inspect decision ${d.id}">Inspect ↗</button></td></tr>`).join('');}
function renderTrend(){const h=state.history;if(!h.length){$('trend').innerHTML='<text x="10" y="80">Start traffic to trace the incident.</text>';return;}const end=Math.max(30000,state.at_ms),path=fn=>h.map((p,i)=>`${i?'L':'M'}${40+p.at_ms/end*930},${130-fn(p)*105}`).join(' ');$('trend').innerHTML=`<path d="M40 25V130H970" fill="none" stroke="#d8e3cf"/><text x="0" y="29">100%</text><text x="15" y="133">0</text><text x="40" y="151">0s</text><text x="930" y="151">${num(end/1000)}s</text><path d="${path(p=>p.essential_success)}" fill="none" stroke="#719063" stroke-width="2.5"/><path d="${path(p=>p.ready/4)}" fill="none" stroke="#b39a63" stroke-width="2" stroke-dasharray="6 5"/><text x="974" y="29">4</text><text x="974" y="132">0</text>`;}
function ingest(next){if(!state||next.at_ms<state.at_ms){seenMotion=next.next_motion;particles=[];lastProgress=next.recovery?.progress_mb||0;}else if(!reducedMotion){for(const m of next.motions){if(m.id<=seenMotion)continue;const i=next.clients.findIndex(c=>c.id===m.client);if(i>=0)particles.push({age:0,duration:1400,from:sourceY(i,next.clients.length),node:m.node,rejected:m.rejected,color:m.rejected?'#b76e53':color(m.client),size:2+Math.sqrt(m.cost_ms/50),transfer:false});}const r=next.recovery;if(r?.phase==='rebuilding'&&r.progress_mb>lastProgress)particles.push({age:0,duration:1800,from:ys[r.source]-10,to:ys[r.target]-10,transfer:true,color:'#b58a4c',size:4});lastProgress=r?.progress_mb||0;seenMotion=next.next_motion;particles=particles.slice(-100);}state=next;connected=true;showError(next.error);render();}
function bezier(a,b,c,d,t){return(1-t)**3*a+3*(1-t)**2*t*b+3*(1-t)*t*t*c+t**3*d;}
function animate(now){const dt=lastFrame?Math.min(80,now-lastFrame):0;lastFrame=now;if(state&&!state.paused&&connected)particles.forEach(p=>p.age+=dt*state.speed);particles=particles.filter(p=>p.age<p.duration);$('flow-particles').innerHTML=particles.map(p=>{const t=p.age/p.duration;let x,y;if(p.transfer){x=bezier(800,950,950,800,t);y=bezier(p.from,p.from,p.to,p.to,t);}else if(t<.45||p.node==null){const u=p.node==null?t:Math.min(1,t/.45);x=bezier(140,245,290,430,u);y=bezier(p.from,p.from,340,340,u);}else{const u=(t-.45)/.55;x=bezier(430,560,590,760,u);y=bezier(340,340,ys[p.node],ys[p.node],u);}return p.transfer?`<rect x="${x-3}" y="${y-3}" width="6" height="6" fill="${p.color}"/>`:`<circle cx="${x}" cy="${y}" r="${p.size}" fill="${p.color}" opacity=".85"/>`;}).join('');requestAnimationFrame(animate);}
async function send(cmd,refresh=false){if(busy)return false;busy=true;revision++;render();try{const r=await fetch('/api/recovery/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cmd),signal:AbortSignal.timeout(10000)}),next=await r.json();if(!r.ok)throw Error(next.error||'Command failed');ingest(next);if(refresh)renderControls(true);return true;}catch(e){showError(e.message);return false;}finally{busy=false;render();}}
async function poll(){if(!busy&&!polling){polling=true;const version=revision;try{const r=await fetch('/api/recovery/state',{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error();const next=await r.json();if(!busy&&version===revision)ingest(next);}catch(e){connected=false;showError('Engine disconnected. Keep the playground CLI running.');render();}finally{polling=false;}}setTimeout(poll,200);}
$('play').onclick=()=>send({type:state.paused?'play':'pause'});$('step').onclick=()=>send({type:'step'});$('reset').onclick=()=>send({type:'reset'},true);$('policy').onchange=e=>send({type:'policy',policy:e.target.value},true);$('scenario').onchange=e=>send({type:'scenario',scenario:e.target.value},true);$('bandwidth').onchange=e=>send({type:'bandwidth',value:+e.target.value});$('add-client').onclick=async()=>{if(await send({type:'add_client'})){selected={kind:'client',id:state.clients.at(-1).id};render();}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.speed)send({type:'speed',value:+b.dataset.speed});if(b.dataset.client!=null){selected={kind:'client',id:+b.dataset.client};render();}if(b.dataset.replica!=null){selected={kind:'replica',id:+b.dataset.replica};render();}if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.decision)inspect(+b.dataset.decision);if(b.id==='heal')send({type:'fault',replica:selected.id,faults:{crashed:false,client_partition:false,transfer_partition:false,slowdown:1,error_rate:0,stale:false}},true);if(b.id==='remove-client')send({type:'remove_client',id:selected.id},true);});
$('controls').addEventListener('input',()=>{controlsDirty=true;});
$('controls').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(e.target.id==='fault-form')send({type:'fault',replica:selected.id,faults:{crashed:f.has('crashed'),client_partition:f.has('client_partition'),transfer_partition:f.has('transfer_partition'),stale:f.has('stale'),slowdown:+f.get('slowdown'),error_rate:+f.get('error_rate')/100}},true);else send({type:'client',id:selected.id,config:{rate:+f.get('rate'),cost_ms:+f.get('cost_ms'),essential_pct:+f.get('essential_pct'),enabled:f.has('enabled')}},true);});
function inspect(id){const d=state.decisions.find(d=>d.id===id);if(!d)return;$('detail-json').textContent=JSON.stringify(d,null,2);$('detail-dialog').showModal();}
$('inspect-latest').onclick=()=>inspect(state.decisions[0]?.id);$('cost-info').onclick=()=>$('cost-dialog').showModal();
document.querySelectorAll('nav a:not([aria-current]),header .brand').forEach(a=>a.addEventListener('click',async e=>{e.preventDefault();if(await send({type:'pause'}))location.href=a.getAttribute('href');}));
const renderLegacyScenario=render;
render=function(){renderLegacyScenario();if(state)window.renderScenarioUI?.({state,busy,connected:connected,selected:selected,send,onSelect:selection=>{selected=selection;renderControls(true); render();}});};
poll();requestAnimationFrame(animate);


$('run-scenario').addEventListener('click',async()=>{const scenario=state.scenario;if(await send({type:'scenario',scenario},true))await send({type:'play'});});

$('forecast-panel').addEventListener('change', e => { if(e.target.id === 'forecast-toggle') send({type:'forecast',enabled:e.target.checked}); });
